<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="2359id-MacAir.local" failures="1" tests="5" name="TestCases.AuthenticationUserSignIn" time="13.363" errors="0" timestamp="19 Jun 2019 07:14:21 GMT" skipped="0">
  <testcase classname="TestCases.AuthenticationUserSignIn" name="A_005_AuthenticationWithEmptyUserName" time="2.488"/>
  <testcase classname="TestCases.AuthenticationUserSignIn" name="A_006_AuthenticationWithEmptyPassword" time="2.498">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at TestCases.AuthenticationUserSignIn.A_006_AuthenticationWithEmptyPassword(AuthenticationUserSignIn.java:236)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:844)
]]>
    </failure>
  </testcase> <!-- A_006_AuthenticationWithEmptyPassword -->
  <testcase classname="TestCases.AuthenticationUserSignIn" name="A_002_AuthenticationWithUnregisteredUserName" time="2.623"/>
  <testcase classname="TestCases.AuthenticationUserSignIn" name="A_003_AuthenticationWithInvalidPassword" time="2.612"/>
  <testcase classname="TestCases.AuthenticationUserSignIn" name="A_001_AuthenticationWithUnregisteredCompanyUser" time="3.142"/>
</testsuite> <!-- TestCases.AuthenticationUserSignIn -->
